[2024-05-22T19:29:24.955+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-22T19:29:24.968+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: disney_api.has_data manual__2024-05-22T19:24:22.802280+00:00 [queued]>
[2024-05-22T19:29:24.977+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: disney_api.has_data manual__2024-05-22T19:24:22.802280+00:00 [queued]>
[2024-05-22T19:29:24.978+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-05-22T19:29:24.990+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): has_data> on 2024-05-22 19:24:22.802280+00:00
[2024-05-22T19:29:24.997+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'disney_api', 'has_data', 'manual__2024-05-22T19:24:22.802280+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/disney_api_dag.py', '--cfg-path', '/tmp/tmpohr8gm22']
[2024-05-22T19:29:24.999+0000] {standard_task_runner.py:91} INFO - Job 30: Subtask has_data
[2024-05-22T19:29:25.001+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3756) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-22T19:29:25.002+0000] {standard_task_runner.py:63} INFO - Started process 3763 to run task
[2024-05-22T19:29:25.041+0000] {task_command.py:426} INFO - Running <TaskInstance: disney_api.has_data manual__2024-05-22T19:24:22.802280+00:00 [running]> on host b4db1197dafa
[2024-05-22T19:29:25.120+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='marcelo.vicente@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='disney_api' AIRFLOW_CTX_TASK_ID='has_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-22T19:24:22.802280+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-22T19:24:22.802280+00:00'
[2024-05-22T19:29:25.121+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-22T19:29:25.130+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-05-22T19:29:25.178+0000] {python.py:237} INFO - Done. Returned value was: processing_data
[2024-05-22T19:29:25.179+0000] {branch.py:36} INFO - Branch into processing_data
[2024-05-22T19:29:25.179+0000] {skipmixin.py:178} INFO - Following branch processing_data
[2024-05-22T19:29:25.192+0000] {skipmixin.py:246} INFO - Skipping tasks [('alarm_dag', -1)]
[2024-05-22T19:29:25.213+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-22T19:29:25.231+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=disney_api, task_id=has_data, run_id=manual__2024-05-22T19:24:22.802280+00:00, execution_date=20240522T192422, start_date=20240522T192924, end_date=20240522T192925
[2024-05-22T19:29:25.257+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-22T19:29:25.279+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-22T19:29:25.285+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
