[2024-05-22T19:29:22.670+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-22T19:29:22.684+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: disney_api.get_data manual__2024-05-22T19:24:22.802280+00:00 [queued]>
[2024-05-22T19:29:22.693+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: disney_api.get_data manual__2024-05-22T19:24:22.802280+00:00 [queued]>
[2024-05-22T19:29:22.695+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-05-22T19:29:22.706+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_data> on 2024-05-22 19:24:22.802280+00:00
[2024-05-22T19:29:22.713+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'disney_api', 'get_data', 'manual__2024-05-22T19:24:22.802280+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/disney_api_dag.py', '--cfg-path', '/tmp/tmpqyylca2e']
[2024-05-22T19:29:22.715+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3752) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-22T19:29:22.715+0000] {standard_task_runner.py:91} INFO - Job 29: Subtask get_data
[2024-05-22T19:29:22.716+0000] {standard_task_runner.py:63} INFO - Started process 3754 to run task
[2024-05-22T19:29:22.756+0000] {task_command.py:426} INFO - Running <TaskInstance: disney_api.get_data manual__2024-05-22T19:24:22.802280+00:00 [running]> on host b4db1197dafa
[2024-05-22T19:29:22.829+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='marcelo.vicente@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='disney_api' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-22T19:24:22.802280+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-22T19:24:22.802280+00:00'
[2024-05-22T19:29:22.830+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-22T19:29:23.636+0000] {logging_mixin.py:188} INFO - df.head: )     _id  ... __v
0  112  ...   0
1   18  ...   0
2   16  ...   0
3   45  ...   0
4    7  ...   0

[5 rows x 15 columns]
[2024-05-22T19:29:23.637+0000] {python.py:237} INFO - Done. Returned value was:     _id  ... __v
0   112  ...   0
1    18  ...   0
2    16  ...   0
3    45  ...   0
4     7  ...   0
5    12  ...   0
6    36  ...   0
7   139  ...   0
8   152  ...   0
9   181  ...   0
10  204  ...   0
11  215  ...   0
12  293  ...   0
13  295  ...   0
14  310  ...   0
15  327  ...   0
16  336  ...   0
17  337  ...   0
18  342  ...   0
19  347  ...   0
20  350  ...   0
21  364  ...   0
22  380  ...   0
23  384  ...   0
24  404  ...   0
25  410  ...   0
26  440  ...   0
27  442  ...   0
28  450  ...   0
29  469  ...   0
30  474  ...   0
31  490  ...   0
32  500  ...   0
33  529  ...   0
34  543  ...   0
35  566  ...   0
36  157  ...   0
37  189  ...   0
38  206  ...   0
39  207  ...   0
40  223  ...   0
41  241  ...   0
42  247  ...   0
43  268  ...   0
44  278  ...   0
45  285  ...   0
46  291  ...   0
47  303  ...   0
48  322  ...   0
49  351  ...   0

[50 rows x 15 columns]
[2024-05-22T19:29:23.691+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-22T19:29:23.730+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=disney_api, task_id=get_data, run_id=manual__2024-05-22T19:24:22.802280+00:00, execution_date=20240522T192422, start_date=20240522T192922, end_date=20240522T192923
[2024-05-22T19:29:23.776+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-22T19:29:23.797+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-22T19:29:23.800+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
