[2024-05-22T19:52:24.050+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-22T19:52:24.062+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: disney_api.has_data manual__2024-05-22T19:52:20.690385+00:00 [queued]>
[2024-05-22T19:52:24.068+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: disney_api.has_data manual__2024-05-22T19:52:20.690385+00:00 [queued]>
[2024-05-22T19:52:24.070+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-22T19:52:24.082+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): has_data> on 2024-05-22 19:52:20.690385+00:00
[2024-05-22T19:52:24.088+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4409) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-22T19:52:24.089+0000] {standard_task_runner.py:63} INFO - Started process 4411 to run task
[2024-05-22T19:52:24.088+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'disney_api', 'has_data', 'manual__2024-05-22T19:52:20.690385+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/disney_api_dag.py', '--cfg-path', '/tmp/tmpp1y72q8y']
[2024-05-22T19:52:24.090+0000] {standard_task_runner.py:91} INFO - Job 39: Subtask has_data
[2024-05-22T19:52:24.128+0000] {task_command.py:426} INFO - Running <TaskInstance: disney_api.has_data manual__2024-05-22T19:52:20.690385+00:00 [running]> on host b4db1197dafa
[2024-05-22T19:52:24.190+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='marcelo.vicente@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='disney_api' AIRFLOW_CTX_TASK_ID='has_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-22T19:52:20.690385+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-22T19:52:20.690385+00:00'
[2024-05-22T19:52:24.192+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-22T19:52:24.200+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-05-22T19:52:24.243+0000] {python.py:237} INFO - Done. Returned value was: processing_data
[2024-05-22T19:52:24.243+0000] {branch.py:36} INFO - Branch into processing_data
[2024-05-22T19:52:24.244+0000] {skipmixin.py:178} INFO - Following branch processing_data
[2024-05-22T19:52:24.257+0000] {skipmixin.py:246} INFO - Skipping tasks [('alarm_dag', -1)]
[2024-05-22T19:52:24.280+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-22T19:52:24.294+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=disney_api, task_id=has_data, run_id=manual__2024-05-22T19:52:20.690385+00:00, execution_date=20240522T195220, start_date=20240522T195224, end_date=20240522T195224
[2024-05-22T19:52:24.344+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-22T19:52:24.364+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-22T19:52:24.367+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
